name: C++ Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Clang 15
        run: sudo apt-get install clang-15

      - name: Install CMake
        run: sudo apt-get install cmake

      - name: Build using CMake
        run: |
          cmake -S . -B build && cmake --build build
