name: C++ Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Clang 16
        run: sudo apt-get install clang-16

      - name: Install CMake
        run: sudo apt-get install cmake

      - name: Build using CMake
        run: |
          cmake -S . -B build -DCMAKE_CXX_STANDARD=23
          cmake --build build

      - name: Test
        run: |
          cd build
          ctest --output-on-failure
          cd ..
