name: C++ Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install GCC with C++23 support
        run: |
          sudo apt-get update
          sudo apt-get install -y g++-13
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 100
          g++ --version

      - name: Install CMake
        run: sudo apt-get install cmake

      - name: Build using CMake with GCC
        run: |
          cmake -S . -B build -DCMAKE_CXX_COMPILER=g++ && cmake --build build
